import { useState } from 'react';
import {
  Search, Plus, ChevronRight, FileText, Download, Share2,
  CheckCircle2, Clock, AlertCircle, Filter, Eye, Tag,
  BookOpen, Shield, FlaskConical, BarChart3, ExternalLink,
  ChevronDown, X, FileBarChart, Layers,
} from 'lucide-react';

/* ── Types ──────────────────────────────────────────────────── */

type ReportStatus = 'published' | 'draft' | 'review' | 'archived';
type ReportType = 'experiment' | 'regulatory' | 'model' | 'analysis' | 'project';

interface Report {
  id: string;
  title: string;
  subtitle: string;
  type: ReportType;
  status: ReportStatus;
  project: string;
  projectColor: string;
  author: string;
  created: string;
  updated: string;
  pages: number;
  tags: string[];
  summary: string;
  sections: { title: string; preview: string }[];
}

/* ── Mock data ──────────────────────────────────────────────── */

const REPORTS: Report[] = [
  {
    id: 'rpt-1',
    title: 'SPF Optimization — Final Candidate Report',
    subtitle: 'Top 3 formulation candidates from multi-objective Bayesian optimization',
    type: 'experiment',
    status: 'published',
    project: 'Sunscreen SPF Optimization',
    projectColor: '#3F98FF',
    author: 'Noble AI Agent · Dr. Sarah Chen',
    created: 'Mar 14, 2026',
    updated: 'Mar 14, 2026',
    pages: 12,
    tags: ['SPF', 'optimization', 'candidates', 'Bayesian'],
    summary: 'Three candidate formulations (R-047, R-089, R-124) were identified via Bayesian optimization over 100 generated recipes. R-047 achieves SPF 52.3 at $18.40/kg with 91.2% water resistance, representing the Pareto-optimal choice across all three objectives.',
    sections: [
      { title: 'Executive Summary', preview: 'Bayesian optimization identified R-047 as the lead candidate with SPF 52.3, water resistance 91.2%, and cost $18.40/kg…' },
      { title: 'Top 3 Formulations', preview: 'R-047: ZnO 14.5%, TiO₂ 8.2%, Avobenzone 3.0% · R-089: ZnO 13.1%, TiO₂ 7.8%, Avobenzone 2.8%…' },
      { title: 'Model Confidence', preview: 'Predictions generated by SPF-XGB-Ensemble v3.0 (R²=0.940, RMSE=2.31). 95% CI for R-047 SPF: [49.4, 55.2]…' },
      { title: 'Regulatory Compliance', preview: 'All three candidates comply with EU Cosmetics Regulation 1223/2009 and ISO 24444:2021 limits…' },
      { title: 'Next Steps', preview: 'Recommend laboratory synthesis and in-vitro SPF testing for R-047 and R-089. Timeline: 2 weeks…' },
    ],
  },
  {
    id: 'rpt-2',
    title: 'EU Cosmetics Regulation — Compliance Summary',
    subtitle: 'EC No 1223/2009 · Annex VI UV filter restrictions and limits',
    type: 'regulatory',
    status: 'published',
    project: 'Sunscreen SPF Optimization',
    projectColor: '#3F98FF',
    author: 'Regulatory Affairs · Dr. J. Müller',
    created: 'Oct 15, 2024',
    updated: 'Mar 12, 2026',
    pages: 8,
    tags: ['regulatory', 'EU', 'compliance', 'UV filters'],
    summary: 'Comprehensive summary of EC No 1223/2009 Annex VI requirements for cosmetic sunscreen UV filters. Covers maximum permitted concentrations, photostability requirements, and labelling obligations for all active UV filters used in the SPF optimization project.',
    sections: [
      { title: 'Applicable Regulation', preview: 'EC No 1223/2009 as amended. Annex VI lists 28 permitted UV filters with max concentrations…' },
      { title: 'UV Filter Limits', preview: 'ZnO nano ≤ 25%; Avobenzone ≤ 5%; Octinoxate ≤ 10%; Titanium Dioxide ≤ 25%…' },
      { title: 'Photostability', preview: 'Photostable formulations must maintain ≥ 90% UV protection after 8h xenon arc exposure…' },
      { title: 'Labelling Requirements', preview: 'SPF claim must be validated per ISO 24444:2021 (in-vivo) or ISO 24443:2021 (in-vitro)…' },
    ],
  },
  {
    id: 'rpt-3',
    title: 'Model Validation Report — SPF-XGB-Ensemble v3.0',
    subtitle: 'Cross-validation, test set performance, and SHAP feature attribution',
    type: 'model',
    status: 'published',
    project: 'Sunscreen SPF Optimization',
    projectColor: '#3F98FF',
    author: 'Noble AI Agent · Dr. Sarah Chen',
    created: 'Mar 14, 2026',
    updated: 'Mar 14, 2026',
    pages: 16,
    tags: ['model', 'validation', 'XGBoost', 'SHAP'],
    summary: 'Full validation report for SPF-XGB-Ensemble v3.0. Achieves R²=0.940 on held-out test set (n=490). 5-fold cross-validation confirms stability (R² σ=0.008). Top SHAP features: ZnO concentration, TiO₂ concentration, pH.',
    sections: [
      { title: 'Model Architecture', preview: 'Ensemble of XGBoost (60% weight) and Random Forest (40% weight). Trained on 1,957 formulations…' },
      { title: 'Cross-Validation', preview: '5-fold CV: R²=[0.932, 0.941, 0.938, 0.947, 0.936]. Mean 0.939, σ 0.008. Stable generalization…' },
      { title: 'Test Set Metrics', preview: 'R²=0.940, RMSE=2.31, MAE=1.71 on n=490 held-out samples. Residuals normally distributed…' },
      { title: 'SHAP Attribution', preview: 'Top features: ZnO_pct (SHAP=0.82), TiO2_pct (0.71), pH (0.34), Avobenzone_pct (0.29)…' },
      { title: 'Bias & Fairness', preview: 'No systematic bias detected across batch ID, lab technician, or date of measurement…' },
    ],
  },
  {
    id: 'rpt-4',
    title: 'Surfactant CMC Prediction — Experiment Summary',
    subtitle: 'Gaussian Process model surrogate validation for CMC prediction',
    type: 'experiment',
    status: 'review',
    project: 'Surfactant CMC Prediction',
    projectColor: '#7c3aed',
    author: 'Dr. R. Patel',
    created: 'Mar 5, 2026',
    updated: 'Mar 10, 2026',
    pages: 10,
    tags: ['CMC', 'surfactant', 'GP', 'uncertainty'],
    summary: 'Experiment summary for the Gaussian Process surrogate model trained on 1,820 CMC measurements. The model achieves R²=0.887 with calibrated 95% confidence intervals. Anionic surfactants show lowest CMC prediction uncertainty.',
    sections: [
      { title: 'Experiment Design', preview: 'GP regression with RBF + White kernel. 10 random restarts, optimized log-marginal likelihood…' },
      { title: 'Model Performance', preview: 'R²=0.887, RMSE=0.24 mM on test set. Uncertainty calibration: 94.2% coverage at 95% CI…' },
      { title: 'Surfactant Subgroups', preview: 'Anionic: R²=0.912; Non-ionic: R²=0.871; Cationic: R²=0.843; Zwitterionic: R²=0.801…' },
    ],
  },
  {
    id: 'rpt-5',
    title: 'Q1 2026 — R&D Progress Summary',
    subtitle: 'Quarterly overview of formulation projects, models, and lab milestones',
    type: 'project',
    status: 'draft',
    project: 'All Projects',
    projectColor: '#059669',
    author: 'Dr. Sarah Chen',
    created: 'Mar 15, 2026',
    updated: 'Mar 15, 2026',
    pages: 6,
    tags: ['quarterly', 'summary', 'R&D', 'milestones'],
    summary: 'Q1 2026 R&D summary covering three active formulation projects. SPF Optimization delivered 3 production-ready candidates. CMC Prediction model deployed to API. Emollient Texture Analysis pending HPO v2.',
    sections: [
      { title: 'SPF Optimization', preview: 'Lead candidate R-047 identified. Model v3.0 deployed. In-vitro testing scheduled for Apr 1…' },
      { title: 'CMC Prediction', preview: 'GP model v1.2 deployed to production API. 94% calibration coverage. 340 API calls this week…' },
      { title: 'Emollient Texture', preview: 'LGBM v1.0 in staging. Pending Optuna HPO v2. ETA production: Apr 14, 2026…' },
    ],
  },
  {
    id: 'rpt-6',
    title: 'UV Filter Photo-Stability Analysis',
    subtitle: 'Degradation kinetics and half-life analysis for 6 UV filter candidates',
    type: 'analysis',
    status: 'draft',
    project: 'UV Filter Photo-Stability',
    projectColor: '#ea580c',
    author: 'Dr. T. Nakamura',
    created: 'Mar 10, 2026',
    updated: 'Mar 15, 2026',
    pages: 9,
    tags: ['photostability', 'degradation', 'UV filter', 'kinetics'],
    summary: 'Photodegradation analysis for 6 UV filter compounds under xenon arc lamp (ICH Q1B). Bemotrizinol shows highest photostability (t½ > 48h). Avobenzone + Octocrylene combination reduces degradation from 38% to 4.2% over 4h.',
    sections: [
      { title: 'Test Protocol', preview: 'ICH Q1B equivalent xenon arc lamp at 550W/m². Measurements at 1h intervals via UV-Vis…' },
      { title: 'Degradation Kinetics', preview: 'First-order kinetics assumed. Half-lives: Bemotrizinol >48h, BEMT 22h, Avobenzone 5.2h…' },
      { title: 'Stabilizer Combinations', preview: 'Octocrylene reduces Avobenzone degradation by 89% at 2% loading. BEMT reduces by 72%…' },
    ],
  },
];

/* ── Config ─────────────────────────────────────────────────── */

const STATUS_CONFIG: Record<ReportStatus, { label: string; color: string; bg: string; dot: string; icon: React.ElementType }> = {
  published: { label: 'Published', color: '#059669', bg: '#f0fdf4', dot: 'bg-green-500', icon: CheckCircle2 },
  draft:     { label: 'Draft',     color: '#9ca3af', bg: '#f9fafb', dot: 'bg-gray-400',  icon: FileText },
  review:    { label: 'In Review', color: '#d97706', bg: '#fffbeb', dot: 'bg-amber-400 animate-pulse', icon: AlertCircle },
  archived:  { label: 'Archived',  color: '#6b7280', bg: '#f9fafb', dot: 'bg-gray-300',  icon: FileText },
};

const TYPE_CONFIG: Record<ReportType, { label: string; icon: React.ElementType; color: string }> = {
  experiment:  { label: 'Experiment',  icon: FlaskConical, color: 'text-blue-600 bg-blue-50' },
  regulatory:  { label: 'Regulatory',  icon: Shield,       color: 'text-green-600 bg-green-50' },
  model:       { label: 'Model',       icon: BarChart3,    color: 'text-purple-600 bg-purple-50' },
  analysis:    { label: 'Analysis',    icon: FileBarChart, color: 'text-orange-600 bg-orange-50' },
  project:     { label: 'Project',     icon: Layers,       color: 'text-teal-600 bg-teal-50' },
};

/* ── Detail panel ───────────────────────────────────────────── */

function ReportDetail({ report, onClose }: { report: Report; onClose: () => void }) {
  const status = STATUS_CONFIG[report.status];
  const type = TYPE_CONFIG[report.type];

  return (
    <div className="w-[44%] border-l border-gray-200 bg-white overflow-auto flex flex-col shrink-0">
      <div className="px-5 py-4 border-b border-gray-200 bg-gray-50 flex items-start justify-between">
        <div>
          <div className="flex items-center gap-2 mb-1.5">
            <span className={`flex items-center gap-1 text-[10px] font-semibold px-2 py-0.5 rounded-full ${type.color}`}>
              <type.icon className="w-3 h-3" />{type.label}
            </span>
            <span className={`flex items-center gap-1 text-[10px] font-semibold px-2 py-0.5 rounded-full`} style={{ backgroundColor: status.bg, color: status.color }}>
              <div className={`w-1.5 h-1.5 rounded-full ${status.dot}`} />
              {status.label}
            </span>
          </div>
          <h2 className="text-base font-bold text-gray-900 leading-tight pr-4">{report.title}</h2>
          <div className="text-xs text-gray-500 mt-0.5">{report.subtitle}</div>
        </div>
        <button onClick={onClose} className="w-6 h-6 flex items-center justify-center rounded text-gray-400 hover:bg-gray-200 transition-colors shrink-0">
          <X className="w-3.5 h-3.5" />
        </button>
      </div>

      <div className="flex-1 overflow-auto p-5 space-y-5">
        {/* Summary */}
        <div>
          <h4 className="text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5">Summary</h4>
          <p className="text-xs text-gray-600 leading-relaxed">{report.summary}</p>
        </div>

        {/* Meta */}
        <div>
          <h4 className="text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-2">Details</h4>
          <div className="grid grid-cols-2 gap-2.5">
            {[
              { label: 'Author', value: report.author },
              { label: 'Created', value: report.created },
              { label: 'Updated', value: report.updated },
              { label: 'Pages', value: `${report.pages} pages` },
            ].map((d) => (
              <div key={d.label} className="bg-gray-50 rounded-lg p-2.5">
                <div className="text-[9px] text-gray-400 uppercase tracking-wide mb-0.5">{d.label}</div>
                <div className="text-[11px] font-semibold text-gray-800 leading-snug">{d.value}</div>
              </div>
            ))}
          </div>
        </div>

        {/* Sections */}
        <div>
          <h4 className="text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-2 flex items-center gap-1.5">
            <BookOpen className="w-3 h-3" /> Contents
          </h4>
          <div className="space-y-2">
            {report.sections.map((sec, i) => (
              <div key={sec.title} className="border border-gray-100 rounded-lg p-3 hover:border-[#3F98FF]/30 hover:bg-blue-50/20 transition-colors cursor-pointer group">
                <div className="flex items-center gap-2 mb-1">
                  <span className="w-4 h-4 rounded bg-gray-100 text-gray-400 text-[9px] font-bold flex items-center justify-center shrink-0 group-hover:bg-[#3F98FF]/10 group-hover:text-[#3F98FF] transition-colors">{i + 1}</span>
                  <span className="text-[11px] font-semibold text-gray-800">{sec.title}</span>
                </div>
                <p className="text-[10px] text-gray-500 leading-relaxed pl-6">{sec.preview}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Tags */}
        <div>
          <h4 className="text-[10px] font-bold text-gray-400 uppercase tracking-wider mb-1.5 flex items-center gap-1">
            <Tag className="w-3 h-3" /> Tags
          </h4>
          <div className="flex flex-wrap gap-1.5">
            {report.tags.map((t) => (
              <span key={t} className="text-[10px] bg-gray-100 text-gray-500 px-2 py-0.5 rounded-full font-medium">#{t}</span>
            ))}
          </div>
        </div>
      </div>

      {/* Actions */}
      <div className="p-4 border-t border-gray-200 bg-gray-50 flex flex-wrap gap-2">
        <button className="flex items-center gap-1.5 px-3 py-2 bg-[#3F98FF] text-white text-xs font-semibold rounded-lg hover:bg-[#2563eb] transition-colors">
          <Eye className="w-3 h-3" /> Open Report
        </button>
        <button className="flex items-center gap-1.5 px-3 py-2 border border-gray-200 text-xs text-gray-600 rounded-lg hover:bg-gray-100 transition-colors">
          <Download className="w-3 h-3" /> Download PDF
        </button>
        <button className="flex items-center gap-1.5 px-3 py-2 border border-gray-200 text-xs text-gray-600 rounded-lg hover:bg-gray-100 transition-colors">
          <Share2 className="w-3 h-3" /> Share
        </button>
        {report.status === 'draft' && (
          <button className="flex items-center gap-1.5 px-3 py-2 border border-green-200 text-xs text-green-600 rounded-lg hover:bg-green-50 transition-colors ml-auto">
            <ExternalLink className="w-3 h-3" /> Publish
          </button>
        )}
      </div>
    </div>
  );
}

/* ── Main page ──────────────────────────────────────────────── */

export function ReportsPage() {
  const [search, setSearch] = useState('');
  const [statusFilter, setStatusFilter] = useState('all');
  const [typeFilter, setTypeFilter] = useState('all');
  const [selectedId, setSelectedId] = useState<string | null>(null);

  const filtered = REPORTS.filter((r) => {
    const matchSearch =
      r.title.toLowerCase().includes(search.toLowerCase()) ||
      r.subtitle.toLowerCase().includes(search.toLowerCase()) ||
      r.tags.some((t) => t.toLowerCase().includes(search.toLowerCase()));
    const matchStatus = statusFilter === 'all' || r.status === statusFilter;
    const matchType = typeFilter === 'all' || r.type === typeFilter;
    return matchSearch && matchStatus && matchType;
  });

  const selectedReport = REPORTS.find((r) => r.id === selectedId) ?? null;

  return (
    <div className="flex-1 overflow-hidden flex flex-col h-full bg-gray-50">
      {/* Header */}
      <div className="bg-white border-b border-gray-200 px-6 py-4 shrink-0">
        <div className="flex items-center justify-between mb-4">
          <div>
            <div className="flex items-center gap-2 text-xs text-gray-400 mb-1">
              <span>Noble AI VIP</span>
              <ChevronRight className="w-3 h-3" />
              <span className="text-gray-600 font-medium">Reports</span>
            </div>
            <h1 className="text-xl font-bold text-gray-900">Reports</h1>
            <p className="text-sm text-gray-500 mt-0.5">Experiment summaries, model validation, and regulatory documentation</p>
          </div>
          <div className="flex items-center gap-2">
            <button className="flex items-center gap-2 px-3 py-2 border border-gray-200 text-gray-600 rounded-lg text-sm font-medium hover:bg-gray-50 transition-colors">
              <Filter className="w-3.5 h-3.5" />
              Filter
            </button>
            <button className="flex items-center gap-2 px-4 py-2 bg-[#3F98FF] text-white rounded-lg text-sm font-medium hover:bg-[#2563eb] transition-colors shadow-sm">
              <Plus className="w-4 h-4" />
              New Report
            </button>
          </div>
        </div>

        {/* Stats */}
        <div className="flex gap-6">
          {[
            { label: 'Total Reports', value: REPORTS.length, color: '#3F98FF' },
            { label: 'Published', value: REPORTS.filter((r) => r.status === 'published').length, color: '#059669' },
            { label: 'In Review', value: REPORTS.filter((r) => r.status === 'review').length, color: '#d97706' },
            { label: 'Drafts', value: REPORTS.filter((r) => r.status === 'draft').length, color: '#9ca3af' },
          ].map((s) => (
            <div key={s.label} className="flex flex-col">
              <div className="text-sm font-bold leading-tight" style={{ color: s.color }}>{s.value}</div>
              <div className="text-[10px] text-gray-400">{s.label}</div>
            </div>
          ))}
        </div>
      </div>

      {/* Main content */}
      <div className="flex-1 overflow-hidden flex">
        <div className={`${selectedId ? 'w-[56%]' : 'flex-1'} overflow-auto p-6 transition-all duration-300`}>

          {/* Filters */}
          <div className="flex items-center gap-3 mb-5 flex-wrap">
            <div className="relative">
              <Search className="w-3.5 h-3.5 text-gray-400 absolute left-2.5 top-1/2 -translate-y-1/2" />
              <input
                type="text"
                placeholder="Search reports..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="pl-8 pr-3 py-1.5 text-sm border border-gray-200 rounded-lg focus:outline-none focus:ring-2 focus:ring-[#3F98FF]/30 focus:border-[#3F98FF] bg-white w-52"
              />
            </div>

            {/* Status filter */}
            <div className="flex items-center gap-1">
              {['all', 'published', 'review', 'draft', 'archived'].map((s) => (
                <button
                  key={s}
                  onClick={() => setStatusFilter(s)}
                  className={`px-2.5 py-1 rounded-md text-xs font-medium capitalize transition-colors ${statusFilter === s ? 'bg-gray-800 text-white' : 'text-gray-500 hover:bg-gray-100'}`}
                >
                  {s === 'all' ? 'All' : STATUS_CONFIG[s as ReportStatus]?.label ?? s}
                </button>
              ))}
            </div>

            {/* Type filter */}
            <div className="relative ml-auto">
              <select
                value={typeFilter}
                onChange={(e) => setTypeFilter(e.target.value)}
                className="appearance-none pl-3 pr-7 py-1.5 text-xs border border-gray-200 rounded-lg bg-white text-gray-600 focus:outline-none focus:ring-2 focus:ring-[#3F98FF]/30 focus:border-[#3F98FF] cursor-pointer"
              >
                <option value="all">All Types</option>
                {Object.entries(TYPE_CONFIG).map(([k, v]) => (
                  <option key={k} value={k}>{v.label}</option>
                ))}
              </select>
              <ChevronDown className="w-3 h-3 text-gray-400 absolute right-2 top-1/2 -translate-y-1/2 pointer-events-none" />
            </div>
          </div>

          {/* Report list */}
          {filtered.length === 0 ? (
            <div className="flex flex-col items-center justify-center h-40 text-center">
              <FileText className="w-8 h-8 text-gray-200 mb-2" />
              <p className="text-sm text-gray-400">No reports match your filters</p>
            </div>
          ) : (
            <div className="space-y-3">
              {filtered.map((report) => {
                const status = STATUS_CONFIG[report.status];
                const type = TYPE_CONFIG[report.type];
                const isSelected = selectedId === report.id;

                return (
                  <div
                    key={report.id}
                    onClick={() => setSelectedId(isSelected ? null : report.id)}
                    className={`bg-white rounded-xl border-2 cursor-pointer transition-all hover:shadow-md group ${isSelected ? 'border-[#3F98FF] shadow-md shadow-[#3F98FF]/10' : 'border-gray-200 hover:border-gray-300'}`}
                  >
                    <div className="p-4">
                      <div className="flex items-start gap-4">
                        {/* Icon */}
                        <div className={`w-10 h-10 rounded-xl flex items-center justify-center shrink-0 ${type.color}`}>
                          <type.icon className="w-5 h-5" />
                        </div>

                        {/* Content */}
                        <div className="flex-1 min-w-0">
                          <div className="flex items-start justify-between gap-3">
                            <div className="flex-1 min-w-0">
                              <div className="flex items-center gap-2 flex-wrap mb-0.5">
                                <span className={`text-[10px] font-semibold px-1.5 py-0.5 rounded-full flex items-center gap-0.5 ${type.color}`}>
                                  <type.icon className="w-2.5 h-2.5" />{type.label}
                                </span>
                                <span
                                  className="flex items-center gap-1 text-[10px] font-semibold px-1.5 py-0.5 rounded-full"
                                  style={{ backgroundColor: status.bg, color: status.color }}
                                >
                                  <div className={`w-1.5 h-1.5 rounded-full ${status.dot}`} />
                                  {status.label}
                                </span>
                              </div>
                              <div className="text-sm font-bold text-gray-900 leading-snug">{report.title}</div>
                              <div className="text-[11px] text-gray-500 mt-0.5">{report.subtitle}</div>
                            </div>

                            {/* Right meta */}
                            <div className="text-right shrink-0">
                              <div className="text-[10px] text-gray-400 flex items-center gap-1 justify-end">
                                <Clock className="w-3 h-3" />{report.updated}
                              </div>
                              <div className="text-[10px] text-gray-400 mt-0.5">{report.pages} pages</div>
                            </div>
                          </div>

                          {/* Summary */}
                          <p className="text-[11px] text-gray-500 mt-2 leading-relaxed line-clamp-2">{report.summary}</p>

                          {/* Footer row */}
                          <div className="flex items-center justify-between mt-3 pt-2.5 border-t border-gray-50">
                            <div className="flex items-center gap-1.5">
                              <div className="w-1.5 h-1.5 rounded-full shrink-0" style={{ backgroundColor: report.projectColor }} />
                              <span className="text-[10px] text-gray-500">{report.project}</span>
                            </div>
                            <div className="flex items-center gap-2 opacity-0 group-hover:opacity-100 transition-opacity" onClick={(e) => e.stopPropagation()}>
                              <button className="flex items-center gap-1 text-[10px] text-gray-400 hover:text-[#3F98FF] transition-colors">
                                <Eye className="w-3 h-3" /> View
                              </button>
                              <button className="flex items-center gap-1 text-[10px] text-gray-400 hover:text-[#3F98FF] transition-colors">
                                <Download className="w-3 h-3" /> PDF
                              </button>
                              <button className="flex items-center gap-1 text-[10px] text-gray-400 hover:text-[#3F98FF] transition-colors">
                                <Share2 className="w-3 h-3" /> Share
                              </button>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Detail panel */}
        {selectedReport && (
          <ReportDetail report={selectedReport} onClose={() => setSelectedId(null)} />
        )}
      </div>
    </div>
  );
}
